# Generated by Django 3.2 on 2022-11-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_orderupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=90)),
                ('mobile_number', models.IntegerField(max_length=10)),
                ('bio', models.CharField(max_length=100)),
            ],
        ),
    ]
